# Generated by Django 4.1 on 2022-08-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='attendee',
            field=models.ManyToManyField(blank=True, to='events.myclubuser'),
        ),
    ]
