# Generated by Django 4.1 on 2022-08-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_myclubuser_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myclubuser',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
    ]
